### ISSUE TITLE
crashes for any input on 32-bit platforms

### ISSUE THREAD

**Issue by imuli** [z7zmey/php-parser#14]
It looks like the problem is with [scanner/lexer.go:465](https://github.com/z7zmey/php-parser/blob/983c721e83bb43d77f3a9bf091cea96c94b637e9/scanner/lexer.go#L465).

```go
        file := token.NewFileSet().AddFile(fName, -1, 1<<31-1)
```

Replacing `1<<31-1` with `1<<30-1` fixes the problem, as does `1<<31-3` (the base of a fileset starts at 1, and adds `size+1` to account for EOF.

The "proper" fix would seem to be
```go
        fInfo, err := os.Stat(fName)
        if err != nil {
            panic(err)
        }
        file := token.NewFileSet().AddFile(fName, -1, int(fInfo.Size())
```

Or passing the file size in from outside. Thoughts?

Error below:

```
panic: token.Pos offset overflow (> 2G of source code in file set)

goroutine 6 [running]:
go/token.(*FileSet).AddFile(0x1a56a150, 0x1a5143c0, 0x40, 0x1, 0x7fffffff, 0x0)
	/nix/store/0b91dwiap82wpar5b225bs8wig8c7xva-go-1.9.2/share/go/src/go/token/position.go:380 +0x291
github.com/z7zmey/php-parser/scanner.NewLexer(0x8d56b10, 0x1a50c178, 0x1a5143c0, 0x40, 0x1a5143c0)
	/home/imuli/src/github.com/z7zmey/php-parser/scanner/lexer.go:465 +0x5a
github.com/z7zmey/php-parser/php7.NewParser(0x8d56b10, 0x1a50c178, 0x1a5143c0, 0x40, 0x0)
	/home/imuli/src/github.com/z7zmey/php-parser/php7/parser.go:32 +0x3d
main.parserWorker(0x1a514200, 0x1a514240)
	/home/imuli/src/github.com/z7zmey/php-parser/main.go:71 +0xf3
created by main.main
	/home/imuli/src/github.com/z7zmey/php-parser/main.go:30 +0xd9
```

**Comment by imuli** [comment]
Well... my so called proper fix means that the filename is required to match an actual file, which obviously isn't the case for all the use cases (my tests started failing when I switched to that one instead of the quick one). I'll make a pull request for the quick one, as we can't reliably get the size out of `src`.
